Name=input("Nama :")
NIM=input("NIM :")
pclass=input("Kelas Paralel :")
TTL=input("Tempat/Tanggal Lahir :")
Alamat=input("Alamat :")
Hobby=input("Hobby :")
phone=input("No.HP :")

print("Nama : ", Name)
print("NIM : ",NIM)
print("Kelas_Paralel : ",pclass)
print("Tempat/Tanggal Lahir : ",TTL)
print("Alamat : ",Alamat)
print("Hobby : ",Hobby)
print("No. HP : ",phone)
print("")