print("##############################")
print("#                            #")
print("#  Ahmad Alif Pratama Putra  #")
print("#       2410817310013        #")
print("#                            #")
print("##############################")